### ISSUE TITLE
Release 2.0.1?

### ISSUE THREAD

**Issue by Freso** [JonnyJD/musicbrainz-isrcsubmit#102]
In 13 days, it will have been a year since the 2.0.0 release. Perhaps consider releasing the 2.0.1? Even if it doesn't have a lot of changes, it does have a couple of bug fixes.

**Comment by JonnyJD** [comment]
Yes, that is on my TODO for quite some time now. I have other deadlines to meet at the moment, but the most important one is in the end of may and I will probably make a new release shortly afterwards.

**Comment by JonnyJD** [comment]
I am back again. Sorry for the delay.

I think I fixed everything that has to go into 2.0.1. I will probably make a release tomorrow or at the weekend.

**Comment by JonnyJD** [comment]
https://github.com/JonnyJD/musicbrainz-isrcsubmit/releases/tag/v2.0.1
