### ISSUE TITLE
"ERROR: cdrdao returned with 1" and no further info

### ISSUE THREAD

**Issue by Freso** [JonnyJD/musicbrainz-isrcsubmit#113]
```
din% isrcsubmit.py --debug --no-keyring
/usr/lib/python3.5/site-packages/keyrings/alt/Gnome.py:28: DeprecationWarning: GnomeKeyring.get_default_keyring_sync is deprecated
  result = GnomeKeyring.get_default_keyring_sync()[0]
Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
isrcsubmit 2.0.1 by JonnyJD for MusicBrainz
INFO: Writing debug log to isrcsubmit.log
INFO: using discid version 1.1.0
using Cdrdao 1.2.3

DiscID:         reTyXYVFkqmFHLU1qzR3s8cXeYQ-
Tracks on disc: 11
INFO: in <ws2:disc>, uncaught <offset-list>
INFO: in <ws2:disc>, uncaught <offset-list>

Artist:         The Axel Boys Quartet
Release:        Everybody Else (Official)
Release Event:  1996            DK
Barcode:        0724385444227
Catalog No.:
MusicBrainz ID: e85185a3-ffd7-4b2a-b9f8-1725ce5185fb

Is this information different for your release?
Would you like to open the browser to submit the disc? [y/N] 

INFO: Saving toc in /tmp/cdrdao-2016-05-03 00-10-20.712139.toc..
ERROR: cdrdao returned with 1
```

I've had this happen for a couple of discs now, and I'm not really sure how to investigate further.

**Comment by JonnyJD** [comment]
Hm, did you try running cdrdao directly:
```
cdrdao read-toc --fast-toc --device <device> -v 0 <tmpfile>
```

**Comment by Freso** [comment]
I'll try the `cdrdao` command when I get home later.

**Comment by Freso** [comment]
Seems like it was the drive being busy. `sudo umount`'ing it did the trick. Perhaps `isrcsubmit.py` could relay the error message(s) from `cdrdao` instead of just saying that it errored with some error code?

**Comment by JonnyJD** [comment]
In general it is good to not hide errors so we shouldn't hide `stderr`.
However, in this case there is output on stderr even when everything runs just fine.
This is what I get on `stderr`:
```
Cdrdao version 1.2.3 - (C) Andreas Mueller <andreas@daneb.de>
```
So this is the reason I hide `stderr`..

We could give stderr in debug mode though.

**Comment by Freso** [comment]
Or perhaps filter stderr and only display messages starting with "`ERROR:`". I'm at a different machine again, so I don't have the exact outputted messages, but I'm pretty sure that the messages started with "`ERROR:`". I can check again when I get home and get the message again.
