### ISSUE TITLE
Documented option “-h” does not display help

### ISSUE THREAD

**Issue by jesus2099** [JonnyJD/musicbrainz-isrcsubmit#115]
I tried with both `isrcsubmit.bat` and `isrcsubmit.py` but none of those displayedd any kind of help:

- `-h` — as documented on the site and in the [README](https://github.com/JonnyJD/musicbrainz-isrcsubmit/blob/b2d5e24892c9f293a040e5189119104cf72d0d33/README.rst)
- `/d` — DOS style
- `--help` — UNIX style
- `-H` — UNIX style

**Comment by Freso** [comment]
```
~/D/M/musicbrainz-isrcsubmit (master)> ./isrcsubmit.py -h
isrcsubmit 2.0.1 by JonnyJD for MusicBrainz

Usage: isrcsubmit.sh [options] [user] [device]
       isrcsubmit.sh -h

Options:
  --version             show program's version number and exit
  -h                    Short usage help
  --help                Complete help for the script
  -u USERNAME, --user=USERNAME
                        MusicBrainz username, if not given as argument.
  -d DEVICE, --device=DEVICE
                        CD device with a loaded audio cd, if not given as
                        argument. The default is /dev/cdrom.
  --release-id=RELEASE_ID
                        Optional MusicBrainz ID of the release. This will be
                        gathered if not given.
  -b PROGRAM, --backend=PROGRAM
                        Force using a specific backend to extract ISRCs from
                        the disc. Possible backends are: mediatools,
                        media_info, cdrdao, libdiscid, discisrc. They are
                        tried in this order otherwise.
  --browser=BROWSER     Program to open URLs. This will be automatically
                        detected for most setups, if not chosen manually.
  --force-submit        Always open TOC/disc ID in browser.
  --server=SERVER       Server to send ISRCs to. Default: musicbrainz.org
  --debug               Show debug messages. Currently shows some backend
                        messages.
  --keyring             Use keyring if available.
  --no-keyring          Disable keyring.
```

Works for me. Can you give some more details about your setup?

**Comment by jesus2099** [comment]
Thanks @Freso, I will try again and see.

**Comment by cdlm** [comment]
In my case I did `pip install isrcsubmit`. Seems like that isn't enough to install the binary dependencies, and I don't think pip reported a problem during the install; `isrcsubmit.py -h` would fail with a stack trace indicating one of the `.so` could not be found. After installing the libs through `pacman`, it seems to work.

**Comment by jesus2099** [comment]
@Freso @JonnyJD 
I found the issue, I think it’s specific to my computer.
I either manually associated `.py` files with `python.exe` or its installation is flawed.
In the `regedit` I found this:

`HKEY_USERS\<some_user_id>\Software\Classes\Applications\python.exe\shell\open\command` = `"C:\Python34\python.exe" "%1"`

And I then changed it to: `"C:\Python34\python.exe" "%1" %*` and now everything is super great!
