### ISSUE TITLE
Getting an error page when I try to submit to musicbrainz

### ISSUE THREAD

**Issue by dragonzeron** [JonnyJD/musicbrainz-isrcsubmit#122]
I keep on getting the message of https://blog.metabrainz.org/2018/02/01/web-service-ver-1-0-ws-1-will-be-removed-in-6-months/ which I dont even know why its on there so

**Comment by dragonzeron** [comment]
can I get a update to see if we can get this working again

**Comment by Freso** [comment]
What are you trying to do exactly? `isrcsubmit` should not be using ws1 anywhere. What version of `isrcsubmit` are you using?

**Comment by Freso** [comment]
I’m going to close this. isrcsubmit 2.x uses ws/2, so should be unaffected by the closing of ws/1. If someone is still using isrcsubmit 1.x… They should update to isrcsubmit 2.x.
