### ISSUE TITLE
Rename main branch to “main”

### ISSUE THREAD

**Issue by Freso** [JonnyJD/musicbrainz-isrcsubmit#141]
GitLab, GitHub, and BitBucket already have this as their default init branch name. I have not seen any compelling reasons _not_ to make this change anywhere, but plenty of reasons _for_ making this change.

See e.g. https://www.nytimes.com/2021/04/13/technology/racist-computer-engineering-terms-ietf.html for background.

**Comment by Freso** [comment]
Looks like I don’t have enough permissions to rename or change the default branch. @JonnyJD something you can look into? :x

**Comment by JonnyJD** [comment]
Done, thanks for the work.
