### ISSUE TITLE
rename repository to "isrcsubmit"?

### ISSUE THREAD

**Issue by JonnyJD** [JonnyJD/musicbrainz-isrcsubmit#80]
The tool is named `isrcsubmit` and I won't change that to musicbrainz-isrcsubmit.

Yes, this is MusicBrainz-related, but even 4 years later (creation of isrcsubmit) I don't see where else one would submit ISRCs.

According to https://github.com/blog/1508-repository-redirects-are-here
renaming should be fine for the repository.
However, github pages don't redirect.
Then again when I re-create the old repository name in order to create a page mentioning where the new page is, I probably cut the redirection of the repository.

This needs at least some testing (test-rename a repository including gh-pages).
Possibly this isn't going to work.

**Comment by jesus2099** [comment]
I wouldn’t do it now.
If I were you, I would test it only when/if you are about to add support for another output. :)
Keeping **musicbrainz** in the name, until then, is adding some visibility to the project.
Removing it will probably make less people find about it.

**Comment by Freso** [comment]
I agree with @jesus2099’s comment. Let’s keep the "musicbrainz" in the name—at least until it actually is able to submit to something other than MB. :)
