### ISSUE TITLE
Log file in wrong location on OS X

### ISSUE THREAD

**Issue by CyberSkull** [JonnyJD/musicbrainz-isrcsubmit#97]
I just noticed that isrcsubmit writes a log file in on OS X. However, it seems to just leave it in my home directory (or working directory, I haven't checked to see what the case is). The correct location for all user logs is in `~/Library/Logs/`, and the file should be put there.

**Comment by JonnyJD** [comment]
You are talking about the debug log (`isrcsubmit.log`)? Not sure if it is a good idea to save the debug log to a non-obvious (not-current) location. The intention is to only run in debug mode if one needs to debug a specific problem and to manually delete the file afterwards. Currently it is written in the working/currrent directory. Writing it to other places probably leads to left over files nobody needs.

The log file is/was not intended for general use. Or do you keep the log file together with ripped files?

Currently no log file is written in normal (non-debug) mode and all temporary files (created with cdrdao backend) should be deleted).

**Comment by CyberSkull** [comment]
I was running debug earlier, but not for the bulk of my work. I was surprised to see the file because there was no notice that a log file was generated.

**Comment by JonnyJD** [comment]
> I was surprised to see the file because there was no notice that a log file was generated.

Indeed, there was no notice. With the latest commit isrcsubmit now gives `INFO: Writing debug log to isrcsubmit.log` in debug mode.

**Comment by CyberSkull** [comment]
That should clear it up. :)
