### ISSUE TITLE
`Y` is not recognized by the prompt in v2.0.0

### ISSUE THREAD

**Issue by CyberSkull** [JonnyJD/musicbrainz-isrcsubmit#98]
I went through and got a bunch of ISRCs ready to submit, and when prompted, I entered `Y` (instead of `y`) and then it replied that nothing had been submitted. 

> Do you want to submit? [y/N] Y
> Nothing was submitted to the server.

So I re-ran the command and when I came to the submit prompt I typed `y` and it worked.

> Do you want to submit? [y/N] y
>
>
> Successfully submitted 24 ISRCS.

**Comment by JonnyJD** [comment]
Indeed we shouldn't be case sensitive here. I'll fix that.

**Comment by JonnyJD** [comment]
Should be fixed with #99

**Comment by CyberSkull** [comment]
All prompts should generally be case insensitive. What I normall do is prior to checking my prompt, I chomp out whitespaces, then if I have a case sensitive comparison function I change my input to lower case and only then compare to my list of valid commands.
